# Generated by Django 5.1.2 on 2025-01-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_crudtracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CRUDTracker',
        ),
    ]
