# Generated by Django 5.1.2 on 2025-01-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_stocknotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockNotification',
        ),
    ]
