# Generated by Django 5.1.2 on 2025-01-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_stockalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
