# Generated by Django 5.1.2 on 2025-01-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
