# Generated by Django 5.1.2 on 2025-01-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_orders_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
