# Generated by Django 5.1.2 on 2025-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
