# Generated by Django 5.1.2 on 2025-01-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
    ]
