# Generated by Django 5.1.2 on 2025-01-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_feedback_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
    ]
