# Generated by Django 5.1.2 on 2025-01-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_feedbacsk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedbacsk',
        ),
    ]
